SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE)AS TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A
    ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY, B.AUTHOR_ID
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC
